services:
  app-dev:
    image: todo-front-dev
    build:
      context: ./todo-frontend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # In Compose, dockerfile paths are resolved from build.context
    volumes:
      - ./todo-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    environment:
      # In dev, Vite runs inside the container, so this can stay a normal runtime env var.
      - VITE_BACKEND_URL=http://localhost:8080/api/
    container_name: todo-front-dev # This will name the container todo-front-dev

  api-dev:
    image: todo-backend-dev
    build:
      context: ./todo-backend/
      dockerfile: dev.Dockerfile
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database # for the Compose network, we use mongo(Docker Compose service name) instead of localhost and 27017 instead of 3456
      REDIS_URL: redis://redis:6379 # for the Compose network, we use redis(Docker Compose service name) instead of localhost and 6379(in this case, it is same as the "external" port)
    depends_on:
      - mongo
      - redis
    volumes:
      - ./todo-backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: todo-api-dev

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: todo-backend-redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD
    volumes:
      - ./todo-backend/redis_data:/data

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
    depends_on:
      - app-dev # wait for the frontend container to be started
      - api-dev
